// Generated by CoffeeScript 1.7.1
(function() {
  var mongoose, _User;

  mongoose = require('mongoose');

  _User = new mongoose.Schema({
    username: String,
    password: String
  });

  module.exports = mongoose.model('User', _User);

}).call(this);

//# sourceMappingURL=User.map
