// Generated by CoffeeScript 1.7.1
(function() {
  var courseEntity, courseModel, db, i, mongoose, _i;

  db = require('../config/database');

  mongoose = require('mongoose');

  courseModel = require("../model/Course");

  for (i = _i = 200002; _i <= 200010; i = ++_i) {
    courseEntity = new courseModel({
      cno: i + '',
      cname: "Thinkins in " + i,
      credit: 6,
      teacher: 'Steve Jobs'
    });
    courseEntity.save();
  }

}).call(this);

//# sourceMappingURL=courseTest.map
