// Generated by CoffeeScript 1.7.1
(function() {
  var db, gradeEntity, gradeModel, mongoose;

  db = require('../config/database');

  mongoose = require('mongoose');

  gradeModel = require("../model/Grade");

  gradeEntity = new gradeModel({
    student: '53b81f0cfb6310cc12ff820f',
    course: '53b8d654805cf358317ff37b',
    score: 90
  });

  gradeEntity.save(function(err) {
    if (err != null) {
      return console.log(err);
    }
  });

}).call(this);

//# sourceMappingURL=gradeTest.map
