// Generated by CoffeeScript 1.7.1
(function() {
  var db, mongoose, studentModel;

  db = require('../config/database');

  mongoose = require('mongoose');

  studentModel = require('../model/Student');

}).call(this);

//# sourceMappingURL=studentTest.map
