// Generated by CoffeeScript 1.7.1
(function() {
  var db, mongoose, user;

  db = require('../config/database');

  mongoose = require('mongoose');

  user = require('../model/user');

  user.findOne({
    username: 1234567890
  }, function(err, data) {
    return console.log(data._id);
  });

}).call(this);

//# sourceMappingURL=userTest.map
