// Generated by CoffeeScript 1.7.1
(function() {
  var db, mongoose, user, userEntity;

  db = require('../config/database');

  mongoose = require('mongoose');

  user = require('../model/user');

  userEntity = new user({
    username: '1234567890',
    password: '123456'
  });

  userEntity.save();

}).call(this);

//# sourceMappingURL=userTest.map
