// Generated by CoffeeScript 1.7.1
(function() {
  var express, gradeModel, router;

  express = require("express");

  router = express.Router();

  gradeModel = require("../model/Grade");

  router.get("/:gid", function(req, res) {
    var gid, query;
    if (req.session.username == null) {
      res.redirect('/');
    }
    gid = req.params.gid;
    query = req.query.query;
    console.log(query);
    return gradeModel.find({}, null, {
      sort: {
        'score': 1
      }
    }, function(err, data) {
      if (err != null) {
        console.log(err);
      }
      console.log(data);
      return res.render('grade', {
        grades: data,
        username: req.session.username,
        query: query,
        status: ''
      });
    });
  });

  router.post("/add", function(req, res) {
    var studentEntity, _birthday, _class, _department, _gender, _sname, _sno;
    if (req.session.username == null) {
      res.redirect('/');
    }
    _sno = req.body.sno;
    _sname = req.body.sname;
    _gender = req.body.gender;
    _class = req.body["class"];
    _department = req.body.department;
    _birthday = req.body.birthday;
    studentEntity = new gradeModel({
      sno: _sno,
      sname: _sname,
      gender: _gender,
      "class": _class,
      department: _department,
      birthday: _birthday
    });
    studentEntity.save(function(err) {
      if (err != null) {
        return console.log(err);
      }
    });
    return res.redirect('/');
  });

  router.get("/delete/:sid", function(req, res) {
    var sid;
    if (req.session.username == null) {
      res.redirect('/');
    }
    sid = req.params.sid;
    console.log(sid);
    gradeModel.remove({
      _id: sid
    }, function(err) {
      if (err != null) {
        return console.log(err);
      }
    });
    return res.redirect('/student');
  });

  router.post("/update/:sid", function(req, res) {
    var sid, _birthday, _class, _department, _gender, _sname, _sno;
    if (req.session.username == null) {
      res.redirect('/');
    }
    sid = req.params.sid;
    _sno = req.body.sno;
    _sname = req.body.sname;
    _gender = req.body.gender;
    _class = req.body["class"];
    _department = req.body.department;
    _birthday = req.body.birthday;
    gradeModel.findByIdAndUpdate(sid, {
      sno: _sno,
      sname: _sname,
      gender: _gender,
      "class": _class,
      department: _department,
      birthday: _birthday
    }, function(err) {
      if (err != null) {
        return console.log(err);
      }
    });
    return res.redirect('/student');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=grade.map
