// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require("express");

  router = express.Router();

  router.get("/", function(req, res) {
    if (req.session.username != null) {
      return res.redirect('/student');
    } else {
      return res.render("login", {
        status: ''
      });
    }
  });

  router.use("/index", function(req, res) {
    if (req.session.username == null) {
      res.redirect('/');
    }
    return res.render('index', {
      username: req.session.username
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.map
