// Generated by CoffeeScript 1.7.1
(function() {
  var express, router, user;

  express = require("express");

  router = express.Router();

  user = require("../model/User");

  router.post("/", function(req, res) {
    var password, username;
    username = req.body.username;
    password = req.body.password;
    return user.find({
      username: username,
      password: password
    }, function(err, user) {
      if (user.length === 0) {
        return res.render('index', {
          status: '<div class="option_result">用户名或密码错误</div>'
        });
      } else {
        return res.json({
          status: 'success'
        });
      }
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=login.map
