// Generated by CoffeeScript 1.7.1
(function() {
  var express, router, studentModel;

  express = require("express");

  router = express.Router();

  studentModel = require("../model/Student");

  router.get("/", function(req, res) {
    var query;
    if (req.session.username == null) {
      res.redirect('/');
    }
    query = req.query.query;
    return studentModel.find({
      "$or": [
        {
          sname: new RegExp(query)
        }, {
          sno: new RegExp(query)
        }, {
          gender: new RegExp(query)
        }, {
          "class": new RegExp(query)
        }, {
          department: new RegExp(query)
        }
      ]
    }, null, {
      sort: {
        'sno': 1
      }
    }, function(err, data) {
      if (err != null) {
        console.log(err);
      }
      return res.render('student', {
        students: data,
        username: req.session.username,
        query: query,
        status: ''
      });
    });
  });

  router.post("/add", function(req, res) {
    var studentEntity, _birthday, _class, _department, _gender, _sname, _sno;
    if (req.session.username == null) {
      res.redirect('/');
    }
    _sno = req.body.sno;
    _sname = req.body.sname;
    _gender = req.body.gender;
    _class = req.body["class"];
    _department = req.body.department;
    _birthday = req.body.birthday;
    studentEntity = new studentModel({
      sno: _sno,
      sname: _sname,
      gender: _gender,
      "class": _class,
      department: _department,
      birthday: _birthday
    });
    studentEntity.save(function(err) {
      if (err != null) {
        return console.log(err);
      }
    });
    return res.redirect('/');
  });

  router.get("/delete/:sid", function(req, res) {
    var sid;
    if (req.session.username == null) {
      res.redirect('/');
    }
    sid = req.params.sid;
    console.log(sid);
    studentModel.remove({
      _id: sid
    }, function(err) {
      if (err != null) {
        return console.log(err);
      }
    });
    return res.redirect('/student');
  });

  router.post("/update/:sid", function(req, res) {
    var sid, _birthday, _class, _department, _gender, _sname, _sno;
    if (req.session.username == null) {
      res.redirect('/');
    }
    sid = req.params.sid;
    _sno = req.body.sno;
    _sname = req.body.sname;
    _gender = req.body.gender;
    _class = req.body["class"];
    _department = req.body.department;
    _birthday = req.body.birthday;
    studentModel.findByIdAndUpdate(sid, {
      sno: _sno,
      sname: _sname,
      gender: _gender,
      "class": _class,
      department: _department,
      birthday: _birthday
    }, function(err) {
      if (err != null) {
        return console.log(err);
      }
    });
    return res.redirect('/student');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=student.map
