// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require("express");

  router = express.Router();

  router.get("/", function(req, res) {
    res.send("respond with a resource");
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.map
