// Generated by CoffeeScript 1.7.1
(function() {
  var mongoDatabaseURI, mongoose;

  mongoose = require('mongoose');

  mongoDatabaseURI = 'mongodb://localhost:27017/studentinfo';

  mongoose.connect(mongoDatabaseURI);

  mongoose.connection.on('connected', function() {
    return console.log('Mongoose default connection open to ' + mongoDatabaseURI);
  });

  mongoose.connection.on('error', function(err) {
    return console.log('Mongoose default connection error: ' + err);
  });

  mongoose.connection.on('disconnected', function() {
    return console.log('Mongoose default connection disconnected');
  });

  require('../model/Student');

  require('../model/Course');

  require('../model/Grade');

}).call(this);

//# sourceMappingURL=database.map
